### ISSUE TITLE
CursorCreate is not responsive after opening; window will not show

### ISSUE THREAD

**Issue by 3raxton** [isaacrobinson2000/CursorCreate#4]
**Describe The Bug:**
Upon download and open the app is rendered unresponsive. Force quits and reinstalls do not work. 

**To Reproduce**
N/A

**Expected Behavior**
CursorCreate should open

**Desktop (please complete the following information):**
 - macOS Big Sur 11.0.1
 - CursorCreate Version: 0.0.0 — I used the latest binary to install and ended up with this version. Not sure if I should have it as 0.0.0
 - Install Method: Pre-packaged binary

**Additional Context:**
I used the latest binary to install and ended up with this version. Not sure if I should have it as 0.0.0

**Comment by isaacrobinson2000** [comment]
Thanks for reaching out! The executable version is an effect of PyInstaller, and I'm not sure if PyInstaller allows you to change it (I will look into it), so I'm pretty sure you have the right version (even though it says 0.0.0). The initial 'tar.gz' you download comes with 2 files, the raw executable and the '.app'. Is there any way you can run the raw executable from the terminal, and paste the output it gives here? One way you can accomplish this is by opening the terminal app and pasting the commands below:
```sh
# Pull down latest version.
curl -L -O https://github.com/isaacrobinson2000/CursorCreate/releases/download/v1.3.1/CursorCreateMac.tar.gz
# Extract it
gunzip -c CursorCreateMac.tar.gz | tar -xopf -
# Execute the raw binary
./CursorCreate
```
That last command should dump some output/errors to the terminal. If you can copy and paste them here it will give me a better idea of why CursorCreate is crashing.

**Comment by llamaWol** [comment]
I have the same issue, same os...
I executed the commands you put above, but it didn't output anything. The app opened but a window didn't come up...

**Comment by 3raxton** [comment]
Following up, I haven't had the chance to look deeply into this yet but will in the next two weeks. Thanks for keeping this issue open. I'll add another comment once I get the chance to take a look at this.

**Comment by isaacrobinson2000** [comment]
Thanks for waiting for a reply, I will also attempt to look into this as soon as I find the time. I suspect it likely has to do with the fact that the Mac Binaries have to pull in the Cairo shared library in order to work properly, and I believe it is dynamically linked to the Mac OS system libraries. Therefore, since I build against Catalina, it doesn't work on Big Sur (I would be curious to see if it fails on other Mac OS versions also). I will have to get up a Big Sur system to test, and that also might allow me to build an executable for Big Sur. (Eventually, a better packaging solution instead of PyInstaller, or removing the CairoSVG dependency should absolve this issue much more gracefully).

**Comment by TheGamer1002** [comment]
Hi! Any fix yet? Same problem, same OS. I'm willing to use my mac as a test dummy.

**Comment by isaacrobinson2000** [comment]
Not yet, haven't had much time to work on it. I'm actively working on trying to get rid of the CairoSVG dependency so this can be resolved. If you like, you can attempt to install the latest version using pip and homebrew or macports and see if you can get it working, in which case It is definitely an issue with the packed executable. I'm willing to give directions if you need help installing it that way. It's not ideal but should provide a way of running it in the meantime while I remove the CairoSVG dependancy.

**Comment by VisualisationExpo** [comment]
I hope there's news soon that will allow CursorCreate open and functioning on macOS Monterey and macOS Big Sur.
Please? 🙂 

I've had no luck with the latest release from May, 2020.

**Comment by isaacrobinson2000** [comment]
I apoligize for not replying until now, as this is honestly the first time I've gotten to look at the project since my last reply. I'd love to work on getting this fixed and running but sadly, I don't have time to work on this project right now (my schedule has only gotten more full), and the changes required to get this working on MacOS are major (forking CairoSVG and replacing all usage of cairo from what I can tell is likely the least time consuming solution).

**Comment by isaacrobinson2000** [comment]
Thank you all for waiting, I finally found some time to work on the project, and the latest release should fix this issue as CairoSVG is now replaced with QWebEngine for SVG rendering. I'll wait to close this issue, and let you test the latest release on Big Sur to make sure it is working as I have a different MacOS version.
